#!/usr/bin/env python3
"""RentTalk Background Intel Scanner v2
- Scans Instagram hashtags, Google News, Reddit
- Matches locations via known UK areas
- Detects AI-generated vs authentic content signals
- Identifies news stations & letting agencies
- Categorises positive vs negative sentiment
- Saves to local JSON + pushes to cloud
- Runs every 15 minutes
"""
import urllib.request, urllib.parse, json, time, os, re, ssl
from datetime import datetime

HOME = os.path.expanduser("~/renttalk")
LOG = os.path.join(HOME, "ig_scan_findings.json")
SCAN_LOG = os.path.join(HOME, "scanner_v2.log")
INTEL_BLOB = "https://jsonblob.com/api/jsonBlob/019d442c-0a2c-793a-8866-9ba75ef5e02c"

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE


# UK location database for matching
UK_LOCATIONS = {
    "London":{"areas":["Central London","East London","West London","North London","South London","Hackney","Brixton","Camden","Islington","Shoreditch","Peckham","Lewisham","Croydon","Hammersmith","Fulham","Kensington","Chelsea","Tower Hamlets","Newham","Barking"],"lat":51.509,"lng":-0.118},
    "Manchester":{"areas":["Salford","Didsbury","Fallowfield","Rusholme","Hulme","Ancoats","Northern Quarter","Chorlton","Withington","Moss Side"],"lat":53.483,"lng":-2.244,"region":"North West"},
    "Birmingham":{"areas":["Edgbaston","Selly Oak","Moseley","Kings Heath","Erdington","Aston","Small Heath"],"lat":52.489,"lng":-1.898,"region":"West Midlands"},
    "Leeds":{"areas":["Headingley","Hyde Park","Chapeltown","Harehills","Kirkstall","Meanwood"],"lat":53.801,"lng":-1.549,"region":"Yorkshire & Humber"},
    "Liverpool":{"areas":["Toxteth","Anfield","Wavertree","Kensington","Aigburth","Smithdown"],"lat":53.408,"lng":-2.991,"region":"North West"},
    "Bristol":{"areas":["Stokes Croft","Easton","Bedminster","Clifton","Cotham","Redland","St Pauls"],"lat":51.454,"lng":-2.587,"region":"South West"},
    "Sheffield":{"areas":["Broomhill","Ecclesall","Sharrow","Heeley","Walkley","Crookes"],"lat":53.381,"lng":-1.470,"region":"Yorkshire & Humber"},
    "Newcastle":{"areas":["Jesmond","Heaton","Byker","Fenham","Gosforth","Elswick"],"lat":54.978,"lng":-1.614,"region":"North East"},
    "Edinburgh":{"areas":["Leith","Gorgie","Dalry","Marchmont","Morningside","Newington"],"lat":55.953,"lng":-3.188,"region":"Scotland"},
    "Glasgow":{"areas":["West End","Partick","Govan","Dennistoun","Shawlands","Maryhill"],"lat":55.864,"lng":-4.252,"region":"Scotland"},
    "Cardiff":{"areas":["Cathays","Roath","Canton","Riverside","Splott","Adamsdown"],"lat":51.481,"lng":-3.179,"region":"Wales"},
    "Brighton":{"areas":["Kemptown","Hanover","Hove","Portslade","Whitehawk"],"lat":50.827,"lng":-0.152,"region":"South East"},
    "Oxford":{"areas":["Cowley","Jericho","Headington","Summertown","Iffley"],"lat":51.752,"lng":-1.258,"region":"South East"},
    "Cambridge":{"areas":["Mill Road","Romsey","Chesterton","Arbury","Cherry Hinton"],"lat":52.205,"lng":0.119,"region":"East of England"},
    "Nottingham":{"areas":["Lenton","Radford","Sneinton","St Anns","Sherwood","Beeston"],"lat":52.954,"lng":-1.158,"region":"East Midlands"},
    "Preston":{"areas":["Deepdale","Plungington","Avenham","Frenchwood"],"lat":53.763,"lng":-2.703,"region":"North West"},
    "Sunderland":{"areas":["Hendon","Millfield","Roker","Seaburn"],"lat":54.906,"lng":-1.381,"region":"North East"},
    "Belfast":{"areas":["Holylands","Botanic","Ormeau","Stranmillis"],"lat":54.597,"lng":-5.930,"region":"Northern Ireland"},
}


# Hashtag rotation — cycles through these each scan
HASHTAG_SETS = [
    ["#badlandlord","#mouldyrental","#ukrent","#rentinguk","#tenantlife"],
    ["#section21","#rentersrights","#nodss","#housingcrisis","#rentcrisis"],
    ["#flathunting","#londonrent","#manchesterrent","#studenthousing","#ukrenting"],
    ["#landlordproblems","#rentersrightsact","#ukproperty","#lettingagent","#depositdispute"],
]

# Known authentic accounts (news, charities, advocacy)
AUTHENTIC_ACCOUNTS = {
    "news": ["bbcnews","skynews","guardian","telegraph","iaborrescamming","channel4news","itv","dailymailuk"],
    "charity": ["sheltercharity","aborrescamming","citizensadvice","generationrent_","acaborrescamming"],
    "advocacy": ["londonrentersunion","acaborrescamming","nrla_uk","propertymark_uk"],
    "local_news": ["manchestereveningnews","liverpoolecho","bristolpost","birminghammail","chroniclelive","yorkshirepost","edinburghlive","waborrescamming"],
}

# AI-generated content signals
AI_SIGNALS = ["midjourney","dalle","aiart","aigenerated","stablediffusion","#ai ","generated by","created with ai"]

# Letting agency keywords for identification
AGENCY_KEYWORDS = ["lettings","letting agent","estate agent","property management","rightmove","zoopla","openrent","spareroom"]

NEG_WORDS = re.compile(r'terrible|awful|horrible|nightmare|unliveable|broken|unsafe|freezing|mould|mold|damp|harass|threaten|evict|stress|anxiety|depress|angry|frustrated|disgusting|filthy|rat|mice|cockroach|scam|rogue|illegal|condemned|uninhabitable|slumlord|crumbling', re.I)
POS_WORDS = re.compile(r'good|great|nice|lovely|fair|reasonable|responsive|helpful|friendly|clean|comfortable|decent|quiet|happy|lucky|excellent|recommend|positive|well.maintained|professional|reliable|honest', re.I)


def log(msg):
    ts = datetime.now().strftime("%H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line)
    with open(SCAN_LOG, 'a') as f:
        f.write(line + "\n")

def load_data():
    try:
        with open(LOG, 'r') as f: return json.load(f)
    except: return {"findings":[],"alerts":[],"agencies":[],"followed":[],"scans":[],"scan_count":0,"last_scan":None}

def save_data(data):
    with open(LOG, 'w') as f: json.dump(data, f, indent=2)

def detect_location(text):
    """Match text against UK location database"""
    found = []
    text_lower = text.lower()
    for city, info in UK_LOCATIONS.items():
        if city.lower() in text_lower:
            found.append({"city":city,"lat":info["lat"],"lng":info["lng"],"region":info.get("region","London")})
        for area in info.get("areas",[]):
            if area.lower() in text_lower:
                found.append({"city":city,"area":area,"lat":info["lat"],"lng":info["lng"],"region":info.get("region","London")})
    return found

def is_ai_content(text):
    """Check for AI-generated content signals"""
    text_lower = text.lower()
    return any(sig in text_lower for sig in AI_SIGNALS)

def detect_sentiment(text):
    neg = len(NEG_WORDS.findall(text))
    pos = len(POS_WORDS.findall(text))
    if neg > pos + 1: return "negative"
    if pos > neg + 1: return "positive"
    if neg > 0 and pos > 0: return "mixed"
    return "neutral"

def detect_agencies(text):
    """Find letting agency or property company mentions"""
    agencies = []
    patterns = [
        r'([A-Z][A-Za-z&\s]{2,25}(?:Lettings|Properties|Homes|Estates|Estate Agents?|Property|Rentals|Management))',
        r'@([a-z_]{3,30}(?:lettings|properties|homes|estates|property|rentals))',
    ]
    for pat in patterns:
        for m in re.finditer(pat, text):
            name = m.group(1).strip() if m.group(1) else m.group(0)
            if len(name) > 4: agencies.append(name)
    return list(set(agencies))


def fetch(url, timeout=10):
    try:
        req = urllib.request.Request(url, headers={"User-Agent":"RentTalk-Scanner/2.0 (research)"})
        return urllib.request.urlopen(req, timeout=timeout, context=ctx).read().decode("utf-8", errors="ignore")
    except Exception as e:
        log(f"  Fetch error: {e}")
        return ""

def scan_reddit(query, limit=8):
    """Scan Reddit for rental discussions"""
    results = []
    for sub in ["HousingUK","LegalAdviceUK","UKPersonalFinance","AskUK"]:
        url = f"https://www.reddit.com/r/{sub}/search.json?q={urllib.parse.quote(query)}&restrict_sr=on&sort=new&limit={limit}&t=month"
        try:
            req = urllib.request.Request(url, headers={"User-Agent":"RentTalk-Scanner/2.0"})
            raw = urllib.request.urlopen(req, timeout=10, context=ctx).read()
            d = json.loads(raw)
            for post in (d.get("data",{}).get("children",[])):
                p = post["data"]
                text = p.get("title","") + " " + p.get("selftext","")[:300]
                locs = detect_location(text)
                sent = detect_sentiment(text)
                agencies = detect_agencies(text)
                if is_ai_content(text): continue
                results.append({
                    "source":"reddit","sub":sub,"title":p.get("title","")[:150],
                    "text":p.get("selftext","")[:300],"url":f"https://reddit.com{p.get('permalink','')}",
                    "score":p.get("score",0),"comments":p.get("num_comments",0),
                    "date":datetime.fromtimestamp(p.get("created_utc",0)).isoformat(),
                    "locations":locs,"sentiment":sent,"agencies":agencies,
                })
            time.sleep(1)
        except: pass
    return results


def scan_news(queries):
    """Scan Google News RSS"""
    results = []
    for q in queries:
        url = f"https://news.google.com/rss/search?q={urllib.parse.quote(q+' UK rental')}&hl=en-GB&gl=GB&ceid=GB:en"
        xml = fetch(url)
        for m in re.finditer(r'<item>.*?<title>(.*?)</title>.*?<link>(.*?)</link>.*?<pubDate>(.*?)</pubDate>.*?<source[^>]*>(.*?)</source>.*?</item>', xml, re.DOTALL):
            title = re.sub(r'<!\[CDATA\[|\]\]>', '', m.group(1)).strip()
            publisher = re.sub(r'<!\[CDATA\[|\]\]>', '', m.group(4)).strip()
            locs = detect_location(title)
            sent = detect_sentiment(title)
            agencies = detect_agencies(title)
            is_authentic_news = any(pub.lower() in publisher.lower() for pub in 
                ["BBC","Sky","Guardian","Telegraph","ITV","Channel 4","Times","Independent",
                 "Evening Standard","Daily Mail","Mirror","Metro","Manchester Evening",
                 "Liverpool Echo","Bristol Post","Birmingham Mail","Chronicle","Yorkshire Post"])
            results.append({
                "source":"news","title":title[:200],"url":m.group(2).strip(),
                "date":m.group(3).strip(),"publisher":publisher,
                "locations":locs,"sentiment":sent,"agencies":agencies,
                "verified_source":is_authentic_news,
            })
        time.sleep(0.5)
    return results

def scan_instagram_via_google(hashtags):
    """Find Instagram posts via Google search (public only)"""
    results = []
    for tag in hashtags:
        clean = tag.replace("#","")
        url = f"https://www.google.com/search?q=site:instagram.com+%23{clean}+uk+rental&num=5&tbs=qdr:m"
        html = fetch(url)
        ig_urls = list(set(re.findall(r'https://www\.instagram\.com/(?:p|reel)/[A-Za-z0-9_-]+/', html)))[:5]
        for ig_url in ig_urls:
            results.append({"source":"instagram","hashtag":tag,"url":ig_url,"verified":False})
        time.sleep(1)
    return results


def create_alert(problem, location, severity, sources, sentiment_breakdown):
    """Create an alert when a problem crosses a threshold"""
    return {
        "ts": datetime.now().isoformat(),
        "problem": problem,
        "location": location,
        "severity": severity,
        "sources_count": len(sources),
        "sentiment": sentiment_breakdown,
        "status": "NEW",
        "sources": sources[:5],
    }

def run_scan(scan_number):
    data = load_data()
    data["scan_count"] = scan_number
    hashtag_set = HASHTAG_SETS[scan_number % len(HASHTAG_SETS)]
    
    log(f"=== SCAN #{scan_number} started ===")
    log(f"  Hashtags: {', '.join(hashtag_set)}")
    
    scan = {
        "ts": datetime.now().isoformat(),
        "number": scan_number,
        "reddit": [], "news": [], "instagram": [],
        "locations_found": [],
        "agencies_found": [],
        "alerts_generated": [],
        "sentiment_summary": {"positive":0,"negative":0,"mixed":0,"neutral":0},
    }

    # 1. Reddit scan
    log("  Scanning Reddit...")
    reddit_queries = ["rent increase UK","mould rental","bad landlord UK","eviction notice","no DSS discrimination"]
    scan["reddit"] = scan_reddit(reddit_queries[scan_number % len(reddit_queries)])
    for r in scan["reddit"]:
        scan["sentiment_summary"][r["sentiment"]] += 1
        scan["locations_found"].extend(r["locations"])
        scan["agencies_found"].extend(r["agencies"])
    log(f"    Reddit: {len(scan['reddit'])} posts")

    # 2. News scan
    log("  Scanning Google News...")
    news_queries = ["UK rent crisis","landlord tenant UK","housing mould UK","renters rights bill 2026","section 21 eviction"]
    scan["news"] = scan_news(news_queries)
    for r in scan["news"]:
        scan["sentiment_summary"][r["sentiment"]] += 1
        scan["locations_found"].extend(r["locations"])
        scan["agencies_found"].extend(r["agencies"])
    log(f"    News: {len(scan['news'])} articles ({sum(1 for a in scan['news'] if a.get('verified_source'))} verified sources)")

    # 3. Instagram via Google
    log("  Scanning Instagram hashtags...")
    scan["instagram"] = scan_instagram_via_google(hashtag_set)
    log(f"    Instagram: {len(scan['instagram'])} posts found")

    # 4. Deduplicate locations and agencies
    seen_locs = set()
    unique_locs = []
    for loc in scan["locations_found"]:
        key = f"{loc['city']}:{loc.get('area','')}"
        if key not in seen_locs:
            seen_locs.add(key)
            unique_locs.append(loc)
    scan["locations_found"] = unique_locs

    seen_agencies = set()
    unique_agencies = []
    for a in scan["agencies_found"]:
        if a.lower() not in seen_agencies:
            seen_agencies.add(a.lower())
            unique_agencies.append(a)
    scan["agencies_found"] = unique_agencies

    # 5. Generate alerts for locations with multiple negative signals
    loc_signals = {}
    for item in scan["reddit"] + scan["news"]:
        for loc in item.get("locations",[]):
            city = loc["city"]
            if city not in loc_signals:
                loc_signals[city] = {"negative":0,"positive":0,"sources":[]}
            if item["sentiment"] == "negative": loc_signals[city]["negative"] += 1
            elif item["sentiment"] == "positive": loc_signals[city]["positive"] += 1
            loc_signals[city]["sources"].append(item.get("title",item.get("text",""))[:80])
    
    for city, signals in loc_signals.items():
        if signals["negative"] >= 2:
            alert = create_alert(
                "Multiple negative reports", city,
                "HIGH" if signals["negative"] >= 4 else "MEDIUM",
                signals["sources"],
                {"negative":signals["negative"],"positive":signals["positive"]}
            )
            scan["alerts_generated"].append(alert)
            data.setdefault("alerts",[]).append(alert)
    
    # 6. Store agencies for tracking
    for a in scan["agencies_found"]:
        if a not in [x["name"] for x in data.get("agencies",[])]:
            data["agencies"].append({"name":a,"first_seen":datetime.now().isoformat(),"mentions":1,"sentiment":"unknown"})
        else:
            for ag in data["agencies"]:
                if ag["name"] == a: ag["mentions"] = ag.get("mentions",0) + 1

    # Save scan
    if "scans" not in data: data["scans"] = []
    data["scans"].append(scan)
    if len(data["scans"]) > 30: data["scans"] = data["scans"][-30:]
    if len(data.get("alerts",[])) > 50: data["alerts"] = data.get("alerts",[])[-50:]
    data["last_scan"] = scan["ts"]
    save_data(data)

    # 7. Push to cloud intel blob
    try:
        req = urllib.request.Request(INTEL_BLOB, headers={"Accept":"application/json"})
        existing = json.loads(urllib.request.urlopen(req, context=ctx).read())
        # Preserve intel_package if it exists
        pkg = existing.get("intel_package")
        existing["social_scans"] = data["scans"][-5:]
        existing["alerts"] = data["alerts"][-10:]
        existing["agencies"] = data.get("agencies",[])[-20:]
        existing["last_social_scan"] = scan["ts"]
        if pkg: existing["intel_package"] = pkg
        put_req = urllib.request.Request(INTEL_BLOB, json.dumps(existing).encode(), method="PUT",
            headers={"Content-Type":"application/json","Accept":"application/json"})
        urllib.request.urlopen(put_req, context=ctx)
        log("  Pushed to cloud")
    except Exception as e:
        log(f"  Cloud push failed: {e}")

    # Summary
    log(f"  Results: {len(scan['reddit'])} reddit, {len(scan['news'])} news, {len(scan['instagram'])} instagram")
    log(f"  Locations: {[l['city'] for l in scan['locations_found']]}")
    log(f"  Agencies: {scan['agencies_found'][:5]}")
    log(f"  Alerts: {len(scan['alerts_generated'])}")
    log(f"  Sentiment: +{scan['sentiment_summary']['positive']} / -{scan['sentiment_summary']['negative']} / ~{scan['sentiment_summary']['neutral']}")
    log(f"=== SCAN #{scan_number} complete ===\n")

if __name__ == "__main__":
    log(f"\n{'='*50}")
    log(f"RentTalk Scanner v2 started")
    log(f"Scanning every 15 minutes")
    log(f"Log: {SCAN_LOG}")
    log(f"Data: {LOG}")
    log(f"{'='*50}\n")
    
    # Kill old scanner if running
    os.system("pkill -f 'scanner.py' 2>/dev/null")
    
    n = 0
    while True:
        try:
            run_scan(n)
            n += 1
        except Exception as e:
            log(f"SCAN ERROR: {e}")
        log(f"Next scan in 15 minutes...\n")
        time.sleep(900)
